# Generated by Django 4.1.13 on 2026-04-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatQA',
        ),
    ]
