# Generated by Django 4.1.13 on 2026-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='store_data',
            field=models.BooleanField(default=True),
        ),
    ]
