# Generated by Django 4.1.13 on 2026-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_chatqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], default='en', max_length=10),
        ),
    ]
