# Generated by Django 4.1.13 on 2026-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_customerbot_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='bot_image',
            field=models.ImageField(blank=True, null=True, upload_to='bot_images/'),
        ),
        migrations.AddField(
            model_name='customerbot',
            name='welcome_message',
            field=models.TextField(default='Hi 👋 How can I help you?'),
        ),
    ]
