# Generated by Django 4.1.13 on 2026-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customerbot_bot_image_customerbot_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='theme_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
    ]
