# Generated by Django 4.1.13 on 2026-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_companypdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='cost_per_request',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=6),
        ),
    ]
