# Generated by Django 4.1.13 on 2026-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_user_balance_user_cost_per_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_prompt_after',
            field=models.IntegerField(default=10),
        ),
    ]
