# Generated by Django 4.1.13 on 2026-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_user_sales_prompt_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sales_prompt_after',
        ),
        migrations.AddField(
            model_name='customerbot',
            name='sales_prompt_after',
            field=models.IntegerField(default=10),
        ),
    ]
