# Generated by Django 4.1.13 on 2026-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_user_sales_prompt_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='instance_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
